---

- name: this contains dynamic variables
  import_playbook: ../dynamic-assignments/env-vars.yml
 
  import_playbook: ../static-assignments/common.yml
  tags:
    - always

- hosts: uat-webservers
- import_playbook: ../static-assignments/uat-webservers.yml

- hosts: db
- name: import database file
  import_playbook: ../static-assignments/db.yml
  tags:
    - always

- hosts: lb
- name: Loadbalancers assignment
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required 