---
- import_playbook: ../static-assignments/common.yml
- import_playbook: ../static-assignments/uat-webservers.yml
- import_playbook: ../static-assignments/mysql.yml

- hosts: lb
  tasks:
    - name: Loadbalancers env var
      include_tasks: ../dynamic-assignments/env-vars.yml

- import_playbook: ../static-assignments/loadbalancers.yml